create database registros;
use registros;

create table alumno(
	id int primary key identity,
	NombreEstudiante varchar(40) not null,
	ApellidoEstudiante varchar(40) not null,
	Grado varchar(20) not null,
	Direccion varchar(200) null,
);
insert into alumno(NombreEstudiante, ApellidoEstudiante, Grado, Direccion) values
/*PRIMERO Básico*/
/*1*/('Astrid Dayana', 'Álvarez de la Cruz', 'Primero Básico','6a. Calle A 14-28 Zona 7, Col. Quinta Samayoa'),
/*2*/('Ana Camila Suceth', 'Amaya Pérez', 'Primero Básico','19 Av. 7-74 Zona 7 Col. Kaminal Juyu I'),
/*3*/('Ángel Manuel', 'Armis', 'Primero Básico','4a. Ca12-07 Zona 7,  Col. Quinta Samayoa'),
/*4*/('Marco Antonio', 'Batres Echeverria', 'Primero Básico','20 Av. 13-30 Zona 7 Col. Kaminla Juyu II'),
/*5*/('Jhorgeysil Ayleen', 'Bonilla', 'Primero Básico','4ta. Calle 13-01 Zona 7 Col. Quinta Samayoa'),
/*6*/('Angie Delyanne', 'Flores Soyoy', 'Primero Básico','14 Av. 6-60 Zona 7 Col. Quinta Samayoa'),
/*7*/('Abi Michelle', 'Gómez Rodríguez', 'Primero Básico','7a. Calle 10-40 Zona 7, Col. Quinta Samayoa'),
/*8*/('Prisly Adairiz', 'González Ordoñez', 'Primero Básico','3ra. Calle B 13-29 Zona 7 Col. Quinta Samayoa'),
/*9*/('Hamilthon Esaú', 'González Sí', 'Primero Básico','6ta. Calle A 10-66 Zona 7, Col. Quinta Samayoa'),
/*10*/('Sharon Alejandra', 'Jiménez Soyoy', 'Primero Básico','13 Av. 7-27 Zona 7, Col. Quinta Samayoa'),
/*11*/('Lisandro Saúl', 'Juárez Escalante', 'Primero Básico','6a. Calle A 13-38 Zona 7, Col. Quinta Samayoa'),
/*12*/('Rosa María', 'Macario Vicente', 'Primero Básico','7a. Calle A 12-24 Zona 7, Col. Quinta Samayoa'),
/*13*/('Tomás Santiago', 'Mateo Sapón', 'Primero Básico','9a. Calle 11-84 Zona 7, Col. Castillo Lara'),
/*14*/('Austin Daniel', 'Montes Arreola', 'Primero Básico','5ta. Calle 13-15 Zona 7, Col. Quinta Samayoa'),
/*15*/('Jeffrey Mateo', 'Natareno Toc', 'Primero Básico','11 Av. 10-64 Zona 7, Col. Castillo Lara'),
/*16*/('Mario Martin', 'Patzán Hernández', 'Primero Básico','5ta. Calle 11-70 Zona 7 Col. Quinta Samayoa'),
/*17*/('Diego Andreé', 'Rodas Zurdo', 'Primero Básico','7a. Calle 14-37 Zona 7, Col. Quinta Samayoa, Zona 7'),
/*18*/('Katherine Mariana', 'Romero Méndez', 'Primero Básico','28 Av. A 23-06 Col. Cuatro de febrero, zona 7'),
/*19*/('Edwin David', 'Roquel Caniche', 'Primero Básico','6ta. Calle 11-24 Zona 7 Col. Quinta Samayoa'),
/*20*/('Norman Isaac', 'Soc Grande', 'Primero Básico','M.  2 Lote 12 Asen. 24 de Dic. Final Col Verbena Z. 7'),
/*21*/('Jennyfer Ximena', 'Váldez Urbina', 'Primero Básico','28 Av. A 23-06 Col. Cuatro de febrero, zona 7'),
/*22*/('Martina Fátima Saraí', 'Rivas Velásquez', 'Primero Básico','3a. Av. 6-18 Zona 7, Col. Landivar'),
/*23*/('Alberth de Jesús', 'Contreras Corea', 'Primero Básico','23 Av. 13-86 Zona 7, Kaminal Juyu II'),
/*24*/('Antoni Vinicio', 'Ismalé Pérez', 'Primero Básico','11 14-80 Zona 7, Col. Castillo Lara '),
/*25*/('Candy Fabiola Odeth', 'Simón Peren', 'Primero Básico','11 CALLE 14-67 Zona 7, Col. Castillo Lara'),
/*26*/('Jhoshua Gamaliel', 'Molina Case', 'Primero Básico','10a. Calle 13-62 Zona 7, Col. Castillo Lara'),
/*27*/('Kiara Julissa Leilany', 'Benito Pérez ', 'Primero Básico','8a. Calle 11-78 Col. Quinta Samayoa'),
/*SEGUNDO Básico*/
/*28*/('Mia Scarlet Susana', 'Carrera Lobos', 'Segundo Básico','19 Av. 13-67 Col. Kaminal Juyu II'),
/*29*/('Candy Mishelle', 'Chocoj Rodríguez', 'Segundo Básico','6ta. Calle A 7-50 Zona 7, Col. Quinta Samayoa '),
/*30*/('Daniela Jimena', 'Fernández Raymundo', 'Segundo Básico','8a. Calle 4-76 Zona 7 Col. Landivar'),
/*31*/('Adam Carlos Enrique', 'Hernández Mendoza', 'Segundo Básico','18 calle 8.01 Zona 7 Col. Verbena'),
/*32*/('Karely Nicole', 'Hernández Vargas', 'Segundo Básico','12 calle 6-15 Zona 7, Col. Verbena'),
/*33*/('Alexandra Anahí Yanet', 'Higueros Burrión', 'Segundo Básico','31. Av. B 23-32 M. 81 Ast. El esfuerzo Zona 7'),
/*34*/('Scarlett Dajane', 'Marroquín Orantes', 'Segundo Básico','11 calle B 11-58 Zona 7 Col. Verbena'),
/*35*/('Melany Anahí', 'Martin Ajiatáz', 'Segundo Básico','11 Av. 12-59 Zona 7 Col. Castillo Lara'),
/*36*/('Kristen Nicol', 'Meletz Carrera', 'Segundo Básico','17 calle 8.69 Zona 7 Col. Verbena'),
/*37*/('Jeremy Alexis', 'Méndez Ijchajchal', 'Segundo Básico','11 Av. 10-53 Zona 7, Col. Castillo Lara'),
/*38*/('Ilbia Rosalia', 'Morales Agustín', 'Segundo Básico','14 calle 9.42 Zona 7, Col. Castillo Lara'),
/*39*/('Pedro Josué', 'Ordoñez Zurdo', 'Segundo Básico','7a. Calle 14-37 Zona 7, Col. Quinta Samayoa, Zona 7'),
/*40*/('Julio Alejandro Jeremiah', 'Ordoñez Zurdo', 'Segundo Básico','7a. Calle 14-37 Zona 7, Col. Quinta Samayoa, Zona 7'),
/*41*/('Sherlin Esmeralda', 'Patzan Díaz', 'Segundo Básico','13 Av. B 31-06 Col. Bethania Zona 7'),
/*42*/('Damaris Anay', 'Rafael Baíl', 'Segundo Básico','7a. Calle A 11-12 Zona 7 Col. Quinta Samayoa'),
/*43*/('Jeferson Omar Israel', 'Rangel Foronda', 'Segundo Básico','13 calle 7a. Av. Final Joya 2, Lote 73 A La Verbena, Z. 7'),
/*44*/('Mildre Aracely', 'Salalá Soyos', 'Segundo Básico','7a. Calle 14-18, Zona 7 Col. Quinta Samayoa'),
/*45*/('Joselyn Mishelle', 'Salala Soyos', 'Segundo Básico','7a. Calle 14-18, Zona 7 Col. Quinta Samayoa'),
/*46*/('Iñaki Lorenzo Antonio', 'Solis Salguero', 'Segundo Básico','13 calle B 18-20 Zona 7 Col. Kaminal Juyup II'),
/*47*/('Kristofer Augusto', 'Toledo Chiquitó', 'Segundo Básico','5ta. Calle 9-13 Zona 7 Col. Quinta Samayoa'),
/*48*/('Londy María', 'Tzul Quiñónez', 'Segundo Básico','13 calle C 25-04 Zona 7, Col. Kaminal Juyup'),
/*49*/('Erick Andrés', 'Yoque Domingo', 'Segundo Básico','8a. Calle C 11-71 Zona 7 Col. Verbena'),
/*50*/('Sharóm Solansh Gabriela', 'Contreras Corea', 'Segundo Básico','23 Av. 13-86 Zona 7, Kaminal Juyu II'),
/*51*/('Ghylaine Cristina', 'Ozuna Barillas', 'Segundo Básico','10 Av. Final Lote 58 Joya 5 Col. Verbena'),
/*52*/('Estefany Paola', 'Morataya Patzán', 'Segundo Básico','8a. Calle 14 Av. 13-89 Zona 7, Quinta Samayoa'),
/*53*/('William Jesús', 'Fernández Reyes', 'Segundo Básico','19 Av. 13-62 Zona 7 Col.  Kaminal II'),
/*54*/('Ligia Virginia', 'Gutiérrez Salazar', 'Segundo Básico','7a. Calle A 10-23 Zona 7, Col. Quinta Samayoa'),
/*TERCERO Básico*/
/*55*/('Gloria Karina', 'Camey Osorio', 'Tercero Básico',''),
/*56*/('Jessica Paola', 'Chaman', 'Tercero Básico','9a. Av. 4-17 Zona 7, Col. Quinta Samayoa'),
/*57*/('Naomi Susana', 'Cuc Gonzáles', 'Tercero Básico',''),
/*58*/('Eddy Randolfo', 'Figueroa Martínez', 'Tercero Básico',''),
/*59*/('Emily Julissa', 'Jocón Barillas', 'Tercero Básico','14 Av. 7-70 Zona 7, Col. Quinta Samayoa'),
/*60*/('Wendy Johana', 'Mauricio López', 'Tercero Básico','Sec. 3 L. 30 Aset. 24 de Dic. Zona 7, Verbena'),
/*61*/('Caterine Helizabeth', 'Méndez Jacobo', 'Tercero Básico',''),
/*62*/('Angelin Daniela', 'Ochoa Quisquina', 'Tercero Básico',''),
/*63*/('Axel Emanuel', 'Ortíz Yax', 'Tercero Básico','L. 11 Sec. 3 Ast. 24 de Dic. , Zona 7, Col. Verbena'),
/*64*/('Cristian Rodolfo', 'Patzán Morales', 'Tercero Básico','7a. Calle 13-13 Zona 7 Col. Quinta Samayoa'),
/*65*/('Axel Eduardo', 'Quisquina Locon', 'Tercero Básico','7a. Calle 11-48 Zona 7, Col. Quinta Samayoa'),
/*66*/('María Elizabeth de la Soledad', 'Saban', 'Tercero Básico','23 Av. 13-86 Zona 7'),
/*67*/('Wilson Alexander', 'Santizo de León', 'Tercero Básico','Col. Bethania'),
/*68*/('Mayda Nicol', 'Sicay Pérez', 'Tercero Básico','10 Av. 13-01 Zona 7, Col. Castillo Lara'),
/*69*/('Angelly Marleni Noemy', 'Subuyuj Morales', 'Tercero Básico','6a. Calle 11-23 Zona 7, Col. Quinta Samayoa'),
/*70*/('Jayra Baneza', 'Tiul Coc', 'Tercero Básico','6ta. Calle A 13-81 Z 7, Col. Quinta Samayoa'),
/*71*/('Jefersón Estiven', 'Váldez Urbina', 'Tercero Básico','12 Av. 4-26 Zona 7 Col. Quinta Samayoa'),
/*72*/('Ángel Ricardo', 'Méndez Chávez', 'Tercero Básico',''),
/*73*/('Katheryn Amarylis', 'Villagrán Mijangos', 'Tercero Básico',''),
/*74*/('Randy Alexander', 'Peren Otzoy', 'Tercero Básico',''),
/*75*/('Maryury Daniela', 'Molina Case', 'Tercero Básico',''),
/*CUARTO BACHILLERATO*/
/*76*/('Lesly Nohemí', 'Ajichiqui Diaz', 'Cuarto Bachillerato',''),
/*77*/('Reina Marisol', 'Castillo Alay', 'Cuarto Bachillerato',''),
/*78*/('Emerson Aimar', 'Higueros Burrión', 'Cuarto Bachillerato',''),
/*79*/('Daniela Abigail', 'Ique González', 'Cuarto Bachillerato',''),
/*80*/('Daphne Ahtziri Desiré', 'Natareno Toc', 'Cuarto Bachillerato',''),
/*81*/('Danna Fernanda', 'Urizar Poroj', 'Cuarto Bachillerato',''),
/*82*/('Edward Steven', 'Mansia Pérez', 'Cuarto Bachillerato',''),
/*83*/('Michael Alexander', 'Xiloj Rueda', 'Cuarto Bachillerato',''),
/*84*/('Yamíli Jimena', 'López Flores', 'Cuarto Bachillerato',''),
/*85*/('Cristofer Misael', 'López Ventura', 'Cuarto Bachillerato',''),
/*86*/('Cristian Manuel', 'Sánchez Pérez', 'Cuarto Bachillerato',''),
/*87*/('Carmen Sarahi', 'Ponce Suchite', 'Cuarto Bachillerato',''),
/*88*/('Franklin Ricardo', 'Velasquez Raxón', 'Cuarto Bachillerato',''),
/*89*/('Dulce María José', 'González Yoc', 'Cuarto Bachillerato',''),
/*QUINTO BACHILLERATO*/
/*90*/('Jaqueline Pamela', 'Barrios Cuyun', 'Quinto Bachillerato',''),
/*91*/('Francisco Jesús', 'Gutiérrez Gálvez', 'Quinto Bachillerato',''),
/*92*/('Cristofer Emilio Alejandro', 'Patzan Díaz', 'Quinto Bachillerato',''),
/*93*/('Rodrigo Alexander', 'Rodas Villeda', 'Quinto Bachillerato',''),
/*94*/('Sharon Dayan', 'Velásquez Cano', 'Quinto Bachillerato','');
create table encargado(
	id int primary key identity,	
	NombreCompletoE1 varchar(200) null,
	NombreCompletoE2 varchar(200) null,
	telefonoE1 int null,
	telefonoE2 int null,
	idalumno int,
	foreign key(idalumno) references alumno(id) on delete cascade
);
insert into encargado(NombreCompletoE1, NombreCompletoE2, telefonoE1,telefonoE2,idalumno) values
/*PRIMERO Básico*/
/*1*/('Yesenia de la Cruz García','','39092709','','1'),
/*2*/('Ingrid Aracely Zelada Chinchilla','','59612899','','2'),
/*3*/('Claudia Armis Boch','María Boch','45381094','39905979','3'),
/*4*/('Jubitza Echeverría Contreras','','50457969','','4'),
/*5*/('Silvia Azucena Bonilla Vanegas','','39134349','','5'),
/*6*/('Julissa Xiomara Soyoy Tuquer','','37096020','','6'),
/*7*/('Marta Julia Rodríguez','','56154185','','7'),
/*8*/('Amalia Muñoz','','51242275','','8'),
/*9*/('María Elvira Sí Tot','','43586033','','9'),
/*10*/('María Fernanda Miranda Paredes','','41446981','','10'),
/*11*/('Gumercinda Concepción Escalante Hernández','','56993330','','11'),
/*12*/('Ana Macario Vicente','','58682459','','12'),
/*13*/('María Maricela Sapón Sulugüi','','32965044','','13'),
/*14*/('Paula Melissa Estrada Arreola','','59321086','','14'),
/*15*/('Domingo Elizabeth Natareno','','35891672','','15'),
/*16*/('Mario Martín Patzán Ortiz','','36921603','','16'),
/*17*/('Andrea Paola Zurdo Batz','','33049629','','17'),
/*18*/('','','','','18'),
/*19*/('Reina Araceli Caniche Nicolás','','51139210','','19'),
/*20*/('Beatriz Soc','','48442237','','20'),
/*21*/('Julia Virginia Urbina  Váldez','','36921477','','21'),
/*22*/('Reyna Josefina Velásquez Ríos','','58335953','','22'),
/*23*/('Karla Corea','','47424386','','23'),
/*24*/('Sandra Pérez','','56934232','','24'),
/*25*/('Elvira Peren Otzoy','','36223361','','25'),
/*26*/('Jonny Gamaliel Molina Contreras','','39092709','','26'),
/*27*/('Jezly Robersy Mirella Benito López','','40063989','','27'),
/*SEGUNDO Básico*/
/*28*/('Verónica Patricia Lobos','','42215210','','28'),
/*29*/('Enma Edelmira Rodríguez Estrada','','56939034','','29'),
/*30*/('Juana Janeth Raymundo Pop','','30100349','','30'),
/*31*/('Linda Ssusset Mendoza Medrano','','38133938','','31'),
/*32*/('Nolvia Liseth Vargas Orellana','','36127776','','32'),
/*33*/('Celia Yaneth Burrión León','','59915415','','33'),
/*34*/('Gloria Mirna Orantes','','50636279','','34'),
/*35*/('Debora Raquel Ajiatás Hernández','','58559961','','35'),
/*36*/('Evelin Marleni Carrera Cruz','','44431110','','36'),
/*37*/('Dolores Ijchajchal Gónzalez','','45232828','','37'),
/*38*/('Ilbia Rosalía Agustín Yol','','37950050','','38'),
/*39*/('Andrea Paola Zurdo Batz','','33049620','48440150','39'),
/*40*/('Andrea Paola Zurdo Batz','','33049620','48440150','40'),
/*41*/('Nancy Maribel Díaz Rueda','Ana María Barrientos','50817240','33355710','41'),
/*42*/('Ofelia Baíl Gómez','','45769306','','42'),
/*43*/('Glenda Patricia Foronda','','59761035','','43'),
/*44*/('María Sandra Soyos Xocoxic','','45744662','','44'),
/*45*/('María Sandra Soyos Xocoxic','','45744662','','45'),
/*46*/('Hilda Salguero','','41859786','','46'),
/*47*/('Aura Estela Chiquitó','','31180246','','47'),
/*48*/('María Nieves García','','51826697','','48'),
/*49*/('Carolina Jasmin Yoque Domingo','','37370430','','49'),
/*50*/('Karla Corea','','47424386','','50'),
/*51*/('Jessica Mariela Ozuna Barillas','','49190774','','51'),
/*52*/('María de los Ángeles Patzán','','42957039','','52'),
/*53*/('Mayra Marilú Reyes Chilin','','59650988','','53'),
/*54*/('Ana Mabely Salazar Flores','','49395804','','54'),
/*TERCERO Básico*/
/*55*/('','','','','55'),
/*56*/('Celia Chamán','','47616125','','56'),
/*57*/('Marly Susana Cuc González','','','','57'),
/*58*/('Mayra Ester Aguilar','Huberto Randolfo Figueroa Natareno','31912974','59003561','58'),
/*59*/('Andrea Betzabé Barillas Villanueva','','49647451','','59'),
/*60*/('Eva López','','46345995','','60'),
/*61*/('Amparo Elizabeth Jacobo Yool','Robin Mendéz','56691790','51853591','61'),
/*62*/('Antonieta Quisquina Locón','','45913845','','62'),
/*63*/('Evelyn Marleni Yax','','50121187','','63'),
/*64*/('Rudy Rodolfo Patzán Gómez','','47616125','','64'),
/*65*/('Antonieta Quisquina Locón','','45913845','','65'),
/*66*/('Victoria Sabán','','45028704','','66'),
/*67*/('','','','','67'),
/*68*/('Fermina Pérez Pérez','','39821733','','68'),
/*69*/('Ana Marleni Morales Castillo','','43393260','','69'),
/*70*/('Hermelindo Tiul Coc','','30444545','','70'),
/*71*/('Julia Urbina','','36921477','','71'),
/*72*/('Juan Ramón Chavez Alvarado','','47619083','','72'),
/*73*/('Juan Carlois Villagrán','','41343873','','73'),
/*74*/('','','','','74'),
/*75*/('Yuvicsa Ninnet Case','','41058068','51100327','75'),
/*CUARTO BACHILLERATO*/
/*76*/('Dominga Díaz','','47467512','','76'),
/*77*/('Veralicia Alay Samayoa','','42645532','','77'),
/*78*/('Celia Yaneth Burrión León','','59915415','','78'),
/*79*/('Daniela Percel Ique','','59761478','50139540','79'),
/*80*/('Dominga Elizabeth Natareno','','35891672','','80'),
/*81*/('','','','','81'),
/*82*/('María del Rosartio Ortiz Rosales','','48117364','','82'),
/*83*/('Reginalda Rueda Florian','','55244412','','83'),
/*84*/('Claudia Elizabet Flores Hernández','','56975230','','84'),
/*85*/('Ofelia López Ventura','','42923734','','85'),
/*86*/('Cristian Manuel Sánchez','','41780069','','86'),
/*87*/('Carmen María Suchite','','51183066','','87'),
/*88*/('Sabrina Siomara Raxón González','','34276693','','88'),
/*89*/('Elsa Eugenia Yoc Xiquin','','55960893','','89'),
/*QUINTO BACHILLERATO*/
/*90*/('Jaqueline Pamela','','57855344','','90'),
/*91*/('Dora Luz Gálvez','','54803230','','91'),
/*92*/('Nancy Maribel Díaz Rueda','Ana María Barrientos','50817240','33355710','92'),
/*93*/('Ingrid Dinora Cifuentes Cruz','','35759655','','93'),
/*94*/('Lesly Saydett Cano','','44589744','','94');
select * from alumno
select NombreCompletoE1 AS 'Nombre completo Encargado 1',NombreCompletoE2 AS 'Nombre completo Encargado 2',telefonoE1 AS 'Telefono 1',telefonoE2 AS 'Telefono 2', a.NombreEstudiante + ' ' + a.ApellidoEstudiante AS 'Nombre estudiante' FROM encargado e
inner join alumno a ON a.id = e.idalumno;

select NombreEstudiante AS 'Nombre del Estudiante', ApellidoEstudiante AS 'Apellido del Estudiante',Grado,Direccion as 'Dirección' from alumno

drop table pagos;
create table pagos(
	id int primary key identity,
	Enero decimal(10,2),
	Febrero decimal(10,2),
	Marzo decimal(10,2),
	Abril  decimal(10,2),
	Mayo  decimal(10,2),
	Junio  decimal(10,2),
	Julio  decimal(10,2),
	Agosto  decimal(10,2),
	Septiembre  decimal(10,2),
	Octubre  decimal(10,2),
	EneroEntregado bit,
	FebreroEntregado bit,
	MarzoEntregado bit,
	AbrilEntregado  bit,
	MayoEntregado  bit,
	JunioEntregado  bit,
	JulioEntregado  bit,
	AgostoEntregado  bit,
	SeptiembreEntregado  bit,
	OctubreEntregado  bit,
	idalumno int,
	idpadre int,
	foreign key(idalumno) references alumno(id),
	foreign key(idpadre) references encargado(id),
);
drop table inscripciones;
create table inscripciones(
	id int identity,
	FechaPago date not null,
	monto decimal(10,2) not null,
	idEstudiante int,
	/*NombreEstudiante varchar(40) not null,
	ApellidoEstudiante varchar(40) not null,
	Grado varchar(20) not null,*/
	idEncargado int,
	/*NombreEncargado varchar(40) not null,
	ApellidoEncargado varchar(40) not null,
	Direccion varchar(80),
	FechaEntrega date,
	MesActual int,
	Enero decimal(10,2),
	Febrero decimal(10,2),
	Marzo decimal(10,2),
	Abril  decimal(10,2),
	Mayo  decimal(10,2),
	Junio  decimal(10,2),
	Julio  decimal(10,2),
	Agosto  decimal(10,2),
	Septiembre  decimal(10,2),
	Octubre  decimal(10,2),*/
	entregado bit,
); 
/*select * from pagos;
select id,NombreEstudiante + ' ' + ApellidoEstudiante AS 'Nombre del alumno',fechaNacimiento from alumno
select a.id,a.NombreEstudiante + ' ' +ApellidoEstudiante AS 'Nombre del alumno',Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre from pagos inner join alumno a on a.id = pagos.idalumno*/

select id AS 'Codigo',Activo,NombreEstudiante AS 'Nombre del Estudiante', ApellidoEstudiante AS 'Apellido del Estudiante',Grado,fechaNacimiento as 'Fecha de Nacimiento',CONCAT(beca,'%') AS '% Beca',direccion as 'Dirección' from alumno
select e.id AS 'Codigo',NombreCompletoE1 AS 'Nombre completo Encargado 1',NombreCompletoE2 AS 'Nombre completo Encargado 2',LEFT(telefonoE1,4) + '-' + RIGHT(telefonoE1,4) AS 'Telefono 1',LEFT(telefonoE2,4) + '-' + RIGHT(telefonoE2,4) AS 'Telefono 2', a.NombreEstudiante + ' ' + a.ApellidoEstudiante AS 'Nombre estudiante' from encargado e INNER JOIN alumno a ON a.id = e.idalumno;
SELECT COUNT(*) from alumno a where activo=1 and grado = 'Tercero Básico';
UPDATE alumno set beca = '0' where beca is null


select DATEDIFF(YEAR,fechanacimiento,GETDATE()) AS 'Edad' from alumno 

select a.id,a.NombreEstudiante + ' ' + a.ApellidoEstudiante AS 'Nombre del alumno',DATEDIFF(YEAR,a.fechanacimiento,GETDATE()) AS 'Edad',CONCAT(a.beca,'%') AS '% Beca',e.NombreCompletoE1,e.NombreCompletoE2,e.telefonoE1,e.telefonoE2
from alumno a inner join encargado e ON a.id = e.idalumno;
